kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-deployer
subjects:
- kind: User
  name: bob@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: service-deployer
  apiGroup: rbac.authorization.k8s.io
