kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-manager
subjects:
- kind: User
  name: alice@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: mesh-manager
  apiGroup: rbac.authorization.k8s.io
